### ISSUE TITLE
Hall mode having problems?

### ISSUE THREAD

**Issue by bhargavah** [Infineon/TLE9879-BLDC-Shield#2]
Hi Guys,

I have read decently on the documentation of TLE9879QXA40 and decided to write some code to control the motor. Happily, I can run the motor in FOC & BEMF mode. However, It does not move in HALL mode. The motor just gives an initial jerk when we send 'startMotor' command. Following is the code for HALL mode.

// Include the Shield library to your Arduino project
#include "TLE9879_Group.h"

#define BOARD1 1

// Declare Shield group object
TLE9879_Group *shields;

void setup()
{
  // Initialize the Shield group object with the
  // number of Shields in the stack
  shields = new TLE9879_Group(1);
  
  // Set the desired mode (FOC, HALL, BEMF)
  // shields->setMode(BEMF);
  
  /*
  shields->setMode(FOC);
  shields->setParameter(FOC_START_ACCEL, 1);
  */

  // /*
  shields->setMode(HALL, BOARD1);
  shields->setParameter(HALL_INIT_DUTY, 30, BOARD1);
  shields->setParameter(HALL_POLE_PAIRS, 4, BOARD1);
  shields->setParameter(HALL_SPEED_KP,500, BOARD1);
  shields->setParameter(HALL_SPEED_KI,100, BOARD1);
  // shields->setParameter(HALL_INPUT_A,0, BOARD1);
  // shields->setParameter(HALL_INPUT_B,1, BOARD1);
  // shields->setParameter(HALL_INPUT_C,2, BOARD1);
  // */

  // Set the desired motor speed (RPM)
  shields->setMotorSpeed(2000, BOARD1);
  /*
  You might have to adjust the motor parameters,
  in case the motor does not run properly.
  */
  // Start the motor and let it run for 5 seconds,
  // then stop the motor
  shields->setMotorMode(START_MOTOR, BOARD1);
  delay(10000);
  shields->setMotorMode(STOP_MOTOR, BOARD1);
}

void loop()
{
}

My motor is 4 pole and is an BLDC. Already checked the hall sensor connections many times with the shield pins. I would be happy to answer more questions, if any.

**Comment by emileb** [comment]
@bhargavah Did you fix this issue? I am experiencing the same problem, hall inputs look OK, tried swapping them etc..
