### ISSUE TITLE
motors take forever to start in hall mode

### ISSUE THREAD

**Issue by ninja-tabouli** [Infineon/TLE9879-BLDC-Shield#3]
Hello, 

I hope you are doing well, I am running a hub brushless motor at 12V and I need to move at very low speeds. Obviously Hall Mode is the only way to achieve that. But I am running into a major problem, the lower I set the speed the speed the more time it takes for the motor to start. At the lowest speed (any lower the motors don't start at all) it took the motor a full 53 second to start turning. I tried adjusting the following parameters: HALL_PWM_FREQ, HALL_INIT_DUTY, HALL_DELAY_MINSPEED but it did not help at all. It feels like a current issue where there is a large current ramp until the amount needed to overcome the torque load is reached. 

please help its a little urgent

**Comment by RupakC22** [comment]
Hello @ninja-tabouli 
We tried to replicate the case at our end. For us the motor reaches a speed of 150 RPM (we tested minimum speed of 150rpm) in less than 5 seconds after the arduino sends the speed command. Can you let us know if you have made any changes to the code? Also, let us know your intended motor speed. 
Also please note that we have used Kp and Ki values of 40 and 20 respectively, for the speed controller. However, these values are based on our motor. You may try to tune these parameters based on your motor specifications. 
Regards
RupakC22
